### ISSUE TITLE
Errors on android build

### ISSUE THREAD

**Issue by mihai-ro** [AgoraIO-Community/Agora-RTC-SDK-for-React-Native#2]
Hello, 
I’m getting these errors when I try to build/run the demo app on an android device.
![1_hf6uintlj4hv3bk_chjqdw](https://user-images.githubusercontent.com/15910058/42746056-ae5da89a-88de-11e8-93d8-c65288ca5ad3.png)

**Comment by dyegooviedo** [comment]
Hello @mihai-ro how did you resolved this?
